apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    appName: {{ .Values.appName }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      appName: {{ .Values.appName }}
  template:
    metadata:
      labels:
        appName: {{ .Values.appName }}
    spec:
      serviceAccountName: {{ .Values.appName }}
      volumes:
        - name: params
          emptyDir: {}
      initContainers:
        - name: ssm-pull
          image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/ssm-pull:latest
          imagePullPolicy: Always
          env:
            - name: PARAMS
              value: {{ .Values.PARAMS | quote }}
            - name: SERVICE_NAME
              value: {{ .Values.appName }}
          volumeMounts:
            - name: params
              mountPath: /data
      containers:
        - name: {{ .Values.appName }}
          image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/{{ .Values.appName }}:{{ .Values.image_tag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.appPort }}
              protocol: TCP
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: params
              mountPath: /data
